# Generated by Django 5.1.15 on 2026-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MERCHANDISE', 'Merchandise Manager'), ('TREASURER', 'Treasurer'), ('VOLUNTEER', 'Volunteer'), ('MEMBER', 'Member')], default='MEMBER', max_length=30),
        ),
    ]
