# Generated by Django 5.1.15 on 2026-10-03 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CULTURAL', 'Cultural & Gala'), ('TECHNICAL', 'Technical & Hackathon'), ('WORKSHOP', 'Workshop & Seminar'), ('SPORTS', 'Sports & Fitness'), ('SOCIAL', 'Social & Networking'), ('CAREER', 'Career & Alumni')], default='CULTURAL', max_length=50)),
                ('venue', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('member_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('non_member_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('registration_open', models.DateTimeField()),
                ('registration_close', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PUBLISHED', max_length=30)),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
