# Generated by Django 5.1.15 on 2026-10-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('APPAREL', 'Apparel & Hoodies'), ('ACCESSORIES', 'Accessories & Caps'), ('STATIONERY', 'Stationery & Notebooks'), ('COLLECTIBLES', 'Badges & Collectibles')], default='APPAREL', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sizes', models.JSONField(blank=True, default=list, help_text="e.g. ['S', 'M', 'L', 'XL', 'XXL']")),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
